version: "3.8"

services:
  liftrecord-db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=liftrecord
      - POSTGRES_USER=liftrecord
      - POSTGRES_DB=liftrecord