openapi: 3.0.0
info:
  title: LiftRecord
  version: '1.0'
servers:
  - url: 'http://localhost:7000'
paths:
  /api/v1/students:
    parameters: []
    post:
      summary: Register new student
      operationId: post-students
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterStudentResponse'
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterStudentRequest'
        description: Corpo da requisicao para cadastrar um novo estudante
      tags:
        - student
  '/api/v1/students/{student_id}/':
    parameters:
      - schema:
          type: string
        name: student_id
        in: path
        required: true
    delete:
      summary: Delete a student
      operationId: delete-students-studentId
      responses:
        '204':
          description: No Content
      description: ''
      tags:
        - student
components:
  schemas:
    RegisterStudentRequest:
      title: RegisterStudentRequest
      type: object
      properties:
        name:
          type: string
        cellphone:
          type: string
        email:
          type: string
        address:
          $ref: '#/components/schemas/RegisterAddressRequest'
      required:
        - name
        - cellphone
        - email
    RegisterAddressRequest:
      title: RegisterAddressRequest
      type: object
      properties:
        state:
          type: string
        city:
          type: string
        street:
          type: string
        neighborhood:
          type: string
        number:
          type: string
        complement:
          type: string
        zip_code:
          type: string
      required:
        - state
        - city
        - street
        - neighborhood
        - number
        - zip_code
    RegisterStudentResponse:
      title: RegisterStudentResponse
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        cellphone:
          type: string
        status:
          type: string
    ErrorResponse:
      title: ErrorResponse
      type: object
      properties:
        message:
          type: string
        status:
          type: string
        uri:
          type: string
      required:
        - message
        - status
        - uri
