openapi: 3.0.0
info:
  title: LiftRecord
  version: '1.0'
servers:
  - url: 'http://localhost:7000'
paths:
  /api/v1/accounts:
    parameters: []
    post:
      summary: Register new account
      operationId: post-api-v1-accounts
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterAccountResponse'
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterAccountRequest'
        description: Corpo da requisicao para cadastrar uma nova conta
      tags:
        - account
  /api/v1/students:
    post:
      summary: ''
      operationId: post-api-v1-students
      responses:
        '201':
          description: Created
      tags:
        - student
  '/api/v1/accounts/{account_id}':
    parameters:
      - schema:
          type: string
        name: account_id
        in: path
        required: true
    delete:
      summary: ''
      operationId: delete-api-v1-accounts-account_id
      responses:
        '204':
          description: No Content
      tags:
        - account
  '/api/v1/students/{student_id}/body-metrics':
    parameters:
      - schema:
          type: string
        name: student_id
        in: path
        required: true
    post:
      summary: ''
      operationId: post-api-v1-students-student_id-body-metrics
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssignBodyMetricsRequest'
      tags:
        - student
components:
  schemas:
    RegisterAccountRequest:
      title: RegisterAccountRequest
      type: object
      properties:
        name:
          type: string
        cellphone:
          type: string
        email:
          type: string
        birth_date:
          type: string
          format: date
        address:
          $ref: '#/components/schemas/RegisterAddressRequest'
      required:
        - name
        - cellphone
        - email
    RegisterAddressRequest:
      title: RegisterAddressRequest
      type: object
      properties:
        state:
          type: string
        city:
          type: string
        street:
          type: string
        neighborhood:
          type: string
        number:
          type: string
        complement:
          type: string
        zip_code:
          type: string
      required:
        - state
        - city
        - street
        - neighborhood
        - number
        - zip_code
    RegisterStudentRequest:
      title: RegisterStudentRequest
      type: object
      properties:
        cnpj:
          type: string
        account_email:
          type: string
    AssignBodyMetricsRequest:
      title: AssignBodyMetricsRequest
      type: object
      properties:
        weight:
          type: number
          format: double
        height:
          type: number
          format: double
        waist_circumference:
          type: number
          format: double
        abdomen_circumference:
          type: number
          format: double
        chest_circumference:
          type: number
          format: double
        arm_circumference:
          type: number
          format: double
        thigh_circumference:
          type: number
          format: double
        hips_circumference:
          type: number
          format: double
        bmi:
          type: number
          format: double
        basal_metabolic_rate:
          type: number
          format: double
    RegisterAccountResponse:
      title: RegisterAccountResponse
      type: object
      properties:
        account_id:
          type: string
        name:
          type: string
        email:
          type: string
        cellphone:
          type: string
        status:
          type: string
        birth_date:
          type: string
          format: date
    ErrorResponse:
      title: ErrorResponse
      type: object
      properties:
        message:
          type: string
        status:
          type: string
        uri:
          type: string
      required:
        - message
        - status
        - uri
