datasources:
  default:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: 'org.postgresql.Driver'
    default:
      enabled: true
jpa:
  default:
    entity-scan:
      classpath: true
      packages:
        - 'br.com.liftrecord.dataaccess.tables'
    packages-to-scan:
      - 'br.com.liftrecord.dataaccess'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
flyway:
  datasources:
    default:
      locations: classpath:db/migration
#  datasources:
#    url: ${DATABASE_URL}
#    username: ${DATABASE_USERNAME}
#    password: ${DATABASE_PASSWORD}
#    driverClassName: 'org.postgresql.Driver'
#    default:
#      enabled: true