micronaut:
  serde:
    property-naming-strategy: SNAKE_CASE
  application:
    name: app-main
    packages:
      - br.com.liftrecord.dataaccess
      - br.com.liftrecord.shared
      - br.com.liftrecord.command
      - br.com.liftrecord.query
      - br.com.liftrecord.domain
      - br.com.liftrecord.infrastrucutre
      - br.com.liftrecord.application
      - br.com.liftrecord.api
      - br.com.liftrecord.bean
      - br.com.liftrecord.app-main
  server:
    port: 7000

jackson:
  property-naming-strategy: SNAKE_CASE

logger:
  levels:
    io.micronaut.context: INFO

datasources:
  default:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
    default:
      enabled: true
jpa:
  default:
    entity-scan:
      packages: br.com.liftrecord.dataaccess.tables
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
flyway:
  datasources:
    url:
    default:
      locations: classpath:db/migration