server:
  port: 7000

spring:
  application:
    name: liftrecord-backend
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    hikari:
      maximum-pool-size: 10
      data-source-properties:
        ### https://jdbc.postgresql.org/documentation/use/#connection-parameters
        reWriteBatchedInserts: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        generate_statistics: false
        format_sql: false
        jdbc:
          batch_size: 25
        order_inserts: true
    open-in-view: false
  task:
    execution:
      pool:
        queue-capacity: 10000

logger:
  levels:
    io.micronaut.context: INFO