server:
  port: 7000
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024

logging:
  level:
    br.com.liftrecord: INFO

spring:
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        ddl-auto: validate
        generate_statistics: false
        format_sql: false
  datasource:
    url: ${database.url:jdbc:postgresql://localhost:5432/liftrecord}?binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: ${database.username:liftrecord}
    password: ${database.password:liftrecord}
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: ${database.url:jdbc:postgresql://localhost:5432/liftrecord}
    user: ${database.username:liftrecord}
    password: ${database.password:liftrecord}