micronaut:
  server:
    port: 3000
  application:
    name: component-test

datasources:
  default:
    db-type: postgres
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES

logger:
  levels:
    io.micronaut.context: INFO